# Generated by Django 5.0.7 on 2024-08-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='old_cart',
        ),
    ]
